name: Deploy storybook to github pages

on: 
  push:
    branches:
      - main

jobs:
  Deploy-storybook:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - name: Install
        run: yarn install

      - name: remove old directory
        run: rm -rf storybook-static

      - name: Build
        run: yarn build-storybook

      - name: Build & deploy
        run: npm run deploy-storybook -- --ci
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}